name: NASA PROJECT WORKFLOW
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
  deploy:
    needs: build
